# Generated by Django 4.1 on 2022-09-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='refugio_image/'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Perfil_Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='refugio_image/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='refugio_image/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='refugio_image/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='refugio_image/')),
                ('refugio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RefugioProf', to='Refugio.refugio')),
            ],
        ),
    ]
