# Generated by Django 4.1 on 2022-09-01 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_mascota_image_alter_mascota_edad_aprox_and_more'),
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_medica',
            name='mascota',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinaria', to='Mascota.mascota'),
        ),
    ]
